### ISSUE TITLE
Prepping for gtsummary v2.0

### ISSUE THREAD

**Issue by ddsjoberg** [openpharma/brms.mmrm#115]
Hello! I am preparing a rather large release for gtsummary and running reverse dependency checks. The checks are timing out for brms.mmrm. I took a look at your use in the vignettes, and I don't think there is a breaking change here and the checks passed locally for me. But wanted to point it out just in case! You can grab the dev version with `pak::pak("ddsjoberg/gtsummary")`. I am looking to make the release in about 3 weeks.

Cheers!

**Comment by wlandau** [comment]
Thanks for the FYI. The vignettes re-render just fine with `gtsummary` 1.9.9.9003. All good from the perspective of `brms.mmrm`.
