### ISSUE TITLE
Subgroup analysis

### ISSUE THREAD

**Issue by wlandau** [openpharma/brms.mmrm#18]
Suggested by @chstock. I picture a model with subgroup and subgroup/treatment interaction and subgroup/treatment/time interaction with the following summaries:

1. Tables like in #8 for each subgroup.
2. Marginal posteriors of each subgroup minus a reference subgroup.

We would also want a test of treatment/subgroup interaction as a whole, c.f. https://github.com/openpharma/mmrm/issues/164.

I think this issue deserves to be addressed eventually, but the base case and informative priors are more important.

**Comment by kkmann** [comment]
-> tern.mmrm does this for mmrm https://github.com/insightsengineering/tern.mmrm

**Comment by wlandau** [comment]
Interesting. Looking at the README, I see:

> Subgroup specific refitting of the MMRM model and resulting forest plot.

Internally at my company for the Bayesian case, so far we fit a single model to all the data with subgroup-specific fixed effects, then show a bunch of posterior summaries of contrasts. We don't use a Bayesian equivalent of https://github.com/openpharma/mmrm/issues/164, and I am not sure if such a method exists, but maybe it would be good to eventually find out.

**Comment by wlandau** [comment]
I plan to start implementing subgroup models soon in order to support internal work.

Statistically, it seems clear enough how to add a subgroup factor to the model and then estimate meaningful subgroup-specific marginal means. From my perspective, the new part is figuring out how to measure the impact of the subgroup as a whole (as opposed to any individual subgroup level).

In the frequentist case, this can be a straightforward model comparison problem: run one model with a subgroup, run a nested model without the subgroup, and compare them with an F test. For Bayesian models, this could easily lead us to Bayes factors. I'm not really a fan of Bayes factors because they are difficult to interpret. As far as the computation goes, bridge sampling is a good as it gets (https://cran.r-project.org/web/packages/bridgesampling/vignettes/bridgesampling_tutorial.pdf) and I have had a lot of trouble using it to compute marginal likelihoods for MMRM-like models.

If we really wanted something like a  Bayes factor, the posterior odds might be more feasible using mixture importance sampling: https://arxiv.org/abs/2209.09190. At the very least, this would require 4 model fits instead of 2, and 2 of those runs would need to have an extra `target += ...` line somewhere in the `model {}` block for mixture IS.

Alternatively, we could straightforwardly list and compare the DIC and/or WAIC of the subgroup model vs the reduced model. These quantities would have serious problems if used for model averaging, but maybe the metrics themselves are enough.

Visually, we could compute the overall marginals of each model (by treatment and visit, averaging over subgroup) and then compare them using `brms.mmrm::brm_plot_compare()`. That might give us an intuitive picture of how much variability is explained by the subgroup.

That covers the standard techniques I am aware of. Am I missing anything? Ideally, for a package like `brms.mmrm`, it would be great to land with one or more tried and true techniques that represent a consensus across our industry.

**Comment by wlandau** [comment]
I think we have everything in place for subgroup so far, unless there are ideas for model comparison techniques other than `brms::waic()` and `brms::loo()`. I will get this merged before Wednesday's Bayesian MMRM sub-team meeting, then work on updating the simulation-based calibration workflow to use subgroup.

**Comment by wlandau** [comment]
It would be great to discuss in tomorrow's meeting what else we might want as far as the subgroup analysis. The functionality is in https://openpharma.github.io/brms.mmrm/articles/subgroup.html, and the validation of the subgroup model part of the "complex scenario" in https://openpharma.github.io/brms.mmrm/articles/sbc.html.

**Comment by wlandau** [comment]
Wrapped up in #79
