### ISSUE TITLE
Conditional means priors

### ISSUE THREAD

**Issue by wlandau** [openpharma/brms.mmrm#40]
We talked about specifying a joint prior on the placebo means or treatment effects, then translating it to an induced prior on any parameterization of regression coefficients. The literature calls this approach "conditional means priors" (CMPs), or BCJ priors after the authors of https://www.jstor.org/stable/2291571, and the topic comes up in prior elicitation. Sources:

* E. Bedrick, R. Christensen, and W. Johnson. A new perspective on priors for generalized linear models. Journal of the American Statistical Association, 91(436):1450–1460, 1996. https://www.jstor.org/stable/2291571.
* E. Bedrick, R. Christensen, and W. Johnson. Bayesian binomial regression: Predicting survival at a trauma center. The American Statistician, 51(3):211–218, 1997.
* R. Christensen, W. Johnson, A. Branscum, T. Hanson. Bayesian Ideas and Data Analysis, CRC Press: Boca Raton. Section 8.4.2.1, p. 203. 2011.
* G. Rosner, P Laud, W. Johnson. Bayesian thinking in biostatistics. CRC Press, 2021.

The method itself is exactly what you would expect: for a model of the form `g(E(y|data)) = X*b` for link function `g()`, and a vector of conditional means `m` such that `g(m) = P*b` given invertible matrix `P`, we specify independent priors on the components of `m` and simply consider the induced prior on `b = P_inverse * g(m)`. The components of `m` become the true parameters of the model, and the regression coefficients in `b` are just transformed parameters. The full augmented model looks like:

```
y ~ MVN(g_inverse(X*b), Sigma)       # likelihood
    b = P_inverse * g(m) # transformation
    m ~ p(...)            # prior
    Sigma ~ LKJ(...)      # prior
```

Since the link `g()` is the identity function, the model collapses down to this:

```
y ~ MVN(Q*m, Sigma)      # likelihood
    m ~ p(...)           # prior
    Sigma ~ LKJ(...)     # prior
```

where `Q = X * P_inverse`. In other words, our true parameters are `m` and `Sigma`. When we do MCMC, we draw joint posterior samples of (`m`, `Sigma`). This seems to be the most feasible (and recommended) way to handle CMPs. The alternative is to analytically transform the joint prior on `m` to a correlated joint prior on `b` beforehand, which seems extremely messy and error-prone even in a specialized case like ours. Then we would need to hack the Stan code of `brms` to implement a custom likelihood family because of the correlated priors on the components of `b`, which is also be extremely messy and error-prone. So unfortunately, I think CMPs force us away from `brms`.

**Comment by wlandau** [comment]
This is really helpful to walk through, @andrew-bean!

I really like the way you calculate `Minv` from `model.matrix()`. Really elegant and easy to do correctly.

So for `fit_cell_contrasts `: it looks like if you nominally regress on `m` but give it contrasts that map to `b`, then the model will actually estimate `b` as parameters. In other words, it actually estimates the contrasts as parameters instead of the individual factor levels. Do I have that right? If so, and if it is possible to give contrasts to the entirety of `group * time`, would conditional means priors be possible using the contrast technique in the reverse direction? It's an interesting connection.

On the other hand, I would find it clearer to manually construct the model matrix and use it in `brm()`. We might have to do that anyway, e.g. if we are adjusting for nuisance covariates and need to manually set a reference level so the components of `m` are not conditional on a subset of the data (e.g. at a level of a nuisance factor, c.f. https://github.com/RConsortium/brms.mmrm/discussions/24#discussioncomment-5928853).

**Comment by wlandau** [comment]
So along the lines of https://github.com/RConsortium/brms.mmrm/issues/40#issuecomment-1643076271:

> For me that correlation seems desirable actually, and it matters for the way historical data would inform a model. With independent priors on the cell means, historical data from one cell would influence the posterior only for that cell. It seems undesirable, because e.g. if you handed me data showing a drug was ineffective at 4 and 8 weeks in a past study, for me it should change my prior for that drug at 12 weeks in a future study.

and https://github.com/RConsortium/brms.mmrm/issues/40#issuecomment-1643910109:

> So then maybe cell means are not always the right choice for m. We might want them to be contrasts of b which
> 
>     1. Are independent, and
>     2. Are intuitive and useful with respect to assigning informative priors.

@andrew-bean and others: if we choose something other than cell means for `m`, what would you propose?

**Comment by weberse2** [comment]
I have not absorbed all content above, but a good read of `factor` contrasts in R is this document:

https://bbolker.github.io/mixedmodels-misc/notes/contrasts.pdf

for MMRMs I think that the `MASS::contr.sdif` contrasts are a really good fit. These are forward differences and allow to define the parameters to mean things like the difference in the visit 3 vs visit 2 being a parameter (consecutive visits). Defining `contrasts` is a very standard thing in R, which is why I consider this as a very attractive way to setup a given parametrisation.

**Comment by wlandau** [comment]
Thanks for the reference, @weberse2. I have always had trouble with contrast notation in R, but maybe I won't after reading that article.

**Comment by wlandau** [comment]
Reading https://bbolker.github.io/mixedmodels-misc/notes/contrasts.pdf, I am reminded of how uncertain I feel when I use the contrast interface and `lme4`-like formulas:

* Did I set the the correct contrast matrix, or do I need its inverse or transpose?
* Am I certain I trust the mapping between the levels of the factor and the columns (rows?) of the contrast matrix? 
* Am I completely confident in how the intercept is handled? Did I put a `-1` index in the right place, or remember to include a `+ 0` in the formula? And if I am looking back at old code and see a `-1` to drop the intercept, is it doing what I think it is doing?
* At what point can I trust the formulas and contrast matrices instead of repeatedly calling `model.matrix()` to check my work?

I may be in the minority, but even after 10+ years of using R to do statistics, I still find it hard to trust that the contrast/formula machinery is faithfully representing a model I have in mind. I would prefer to set up the regression coefficients in a more explicit and pedantic way, with transparent/verbose assurances, and strict guardrails (in our case, simple objects passed to well-documented fit-for-purpose formal arguments).

**Comment by weberse2** [comment]
I do understand your concerns with the R contrast system, which is not super intuitive. It's just that a lot of R works in this way and going against this established system is a choice to make. However, you are probably right in that the majority of people are anyway not familiar with these conventions in R and it is hence better to create your own one.

**Comment by wlandau** [comment]
Taking a step back and revisiting https://github.com/openpharma/brms.mmrm/issues/40#issuecomment-1643995915, I wonder if explicit CMPs are even necessary for our identity link function. As @andrew-bean observed, the model matrix just collapses back down into a different model matrix. In that situation, I would think it is more efficient to choose whatever prior-friendly parameterization makes sense (for example, cell means) and then compute quantities like the intercept as transformed parameters if needed.

Of course, if we want our priors on fixed effects to be correlated, that might complicate things. But are correlated priors be necessary to consider? Seems like a challenge to account for correlations between different time points in the prior, especially if we need to elicit that prior. And we already have a flexible correlation matrix on the residuals.

**Comment by weberse2** [comment]
Well... if you are going for non-informative priors then cell means are easy and simple to set up... in practice I'd much prefer to put a prior on the difference in the response from visit to visit. This isn't big usually and it creates immediately a correlation structure which is appropriate for the problem at hand in many cases.

**Comment by wlandau** [comment]
Coming back to this after almost a year, I think it would help to list all the major cases we care about for assigning priors. I can think of priors on:

1. The difference in response from visit to visit.
2. Cell means.
3. Cell means for placebo response, but effects for treatment.

Any others?

**Comment by wlandau** [comment]
For this issue, we seem to be heading away from conditional means priors and towards reparameterization in general. In the original formulation by Bedrick et al., CMPs are about using elicited priors on the response scale to induce priors on the model coefficients. We don't actually need that here. All we need is a model that has a parameterization amenable to informative priors. Beyond that point, any deterministic function on posterior samples is straightforward.

**Comment by wlandau** [comment]
Moving this to a discussion in favor of #96.
