### ISSUE TITLE
First CRAN submission

### ISSUE THREAD

**Issue by wlandau** [openpharma/brms.mmrm#51]
I think we will be ready for a first CRAN submission after #36 and #43. As we discussed, this would help users try the package, which might even help with validation. As the disclaimer in the README states, the package is not validated, so I think the version number could be something like 0.0.1 instead of 1.0.0. How does that all sound?

**Comment by chstock** [comment]
Sounds very good!

**Comment by yonicd** [comment]
Sounds great. I’ll dig into emmeans a bit more to try and see how nuisance params are handled. In general i think that emneans is a lot like broom in architecture, methods that are amenable to extension by other developers. This would mean any posterior logic isn’t in emmeans itself.

**Comment by wlandau** [comment]
Thanks @yonicd! That would really help! I will post an issue.

**Comment by wlandau** [comment]
c.f. #53

**Comment by wlandau** [comment]
Submitted to CRAN!
