### ISSUE TITLE
Comparison of brms.mmrm and mmrm: orthodont dataset

### ISSUE THREAD

**Issue by chstock** [openpharma/brms.mmrm#66]
I fitted MMRMs to the **[orthodont](https://github.com/openpharma/brms.mmrm/issues/11#issuecomment-1719980792)** dataset using both `mmrm::mmrm()` and `brms.mmrm::brm_model()`.  Apologies, the reprex has become a bit lengthy. Of note, the endpoint here is a `response`, not a `chg`-variable. I noted a few things that are summarized below:

**Prerequisites**
```r
packages <- c("tidyr",  "dplyr", "stringr", "tictoc", "nlme")
invisible(lapply(packages, library, character.only = T))
library(brms.mmrm) # version brms.mmrm_0.0.2.9001
library(mmrm) #  mmrm_0.3.3
set.seed(123L)
```

**Data**
```r
# data
data(Orthodont)
# age variable: brms.mmrm needs a character or factor 'time' variable
Orthodont$age_fct <- as.character(Orthodont$age)
Orthodont$age_fct[which(Orthodont$age_fct == "8")] <- "08" # changed as otherwise age = "10" becomes the reference level
Orthodont$age_fct <- factor(Orthodont$age_fct)
levels(Orthodont$age_fct)
#> [1] "08" "10" "12" "14"
# sex variable: reference level changed since `level_control` in brm_data() did not seem be effective
levels(Orthodont$Sex)
#> [1] "Male"   "Female"
Orthodont$Sex <- relevel(Orthodont$Sex, ref = "Female")
levels(Orthodont$Sex)
#> [1] "Female" "Male"
lapply(Orthodont, class) |> unlist()
#>  distance       age  Subject1  Subject2       Sex   age_fct 
#> "numeric" "numeric" "ordered"  "factor"  "factor"  "factor"
head(Orthodont)
#> Grouped Data: distance ~ age | Subject
#>   distance age Subject  Sex age_fct
#> 1     26.0   8     M01 Male      08
#> 2     25.0  10     M01 Male      10
#> 3     29.0  12     M01 Male      12
#> 4     31.0  14     M01 Male      14
#> 5     21.5   8     M02 Male      08
#> 6     22.5  10     M02 Male      10
```

**mmrm**
```r
mmrm_fit <- mmrm(
  formula = distance  ~ age_fct + Sex * age_fct + us(age_fct | Subject),
  data = Orthodont,
  control = mmrm_control(method = "Satterthwaite")
)
summary(mmrm_fit)
#> mmrm fit
#> 
#> Formula:     distance ~ age_fct + Sex * age_fct + us(age_fct | Subject)
#> Data:        Orthodont (used 108 observations from 27 subjects with maximum 4 
#> timepoints)
#> Covariance:  unstructured (10 variance parameters)
#> Method:      Satterthwaite
#> Vcov Method: Asymptotic
#> Inference:   REML
#> 
#> Model selection criteria:
#>      AIC      BIC   logLik deviance 
#>      434      447     -207      414 
#> 
#> Coefficients: 
#>                   Estimate Std. Error      df t value Pr(>|t|)    
#> (Intercept)        21.1818     0.7017 25.0000  30.189  < 2e-16 ***
#> age_fct10           1.0455     0.6155 25.0000   1.699 0.101793    
#> age_fct12           1.9091     0.6068 25.0000   3.146 0.004241 ** 
#> age_fct14           2.9091     0.6729 25.0000   4.323 0.000215 ***
#> SexMale             1.6932     0.9115 25.0000   1.858 0.075038 .  
#> age_fct10:SexMale  -0.1080     0.7995 25.0000  -0.135 0.893671    
#> age_fct12:SexMale   0.9347     0.7883 25.0000   1.186 0.246904    
#> age_fct14:SexMale   1.6847     0.8741 25.0000   1.927 0.065385 .  
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> Covariance estimate:
#>        08     10     12     14
#> 08 5.4155 2.7168 3.9102 2.7102
#> 10 2.7168 4.1848 2.9272 3.3172
#> 12 3.9102 2.9272 6.4557 4.1307
#> 14 2.7102 3.3172 4.1307 4.9857
```

**brms.mmrm**
```r
# Pre-process dataset
brms.mmrm_data <- brm_data(
  data = Orthodont, 
  outcome = "distance",
  role = "response",
  group = "Sex",
  time = "age_fct",
  patient = "Subject",
  baseline = NULL,
  level_control = "Female", # an effect for 'sexMale' is shown for both "Male" and "Female"
  level_baseline = "08" # an error occurs if set to NULL
)
# Model formula
brms.mmrm_formula <- brm_formula(
  data = brms.mmrm_data,
  intercept = TRUE,
  effect_baseline = FALSE,
  effect_group = TRUE,
  effect_time = TRUE,
  interaction_baseline = TRUE,
  interaction_group = TRUE,
  correlation = "unstructured"
)
print(brms.mmrm_formula)
#> distance ~ age_fct + Sex + Sex:age_fct + unstr(time = age_fct, gr = Subject) 
#> sigma ~ 0 + age_fct
# Model fit
options(mc.cores = 3)
tic()
brms.mmrm_fit <- brm_model(
  data = brms.mmrm_data,
  formula = brms.mmrm_formula,
  chains = 3,
  iter = 2000,
  refresh = 0,
  cores = 3
  )
toc()
#> 155.63 sec elapsed

summary(brms.mmrm_fit)
#>  Family: gaussian 
#>   Links: mu = identity; sigma = log 
#> Formula: distance ~ age_fct + Sex + Sex:age_fct + unstr(time = age_fct, gr = Subject) 
#>          sigma ~ 0 + age_fct
#>    Data: data (Number of observations: 108) 
#>   Draws: 3 chains, each with iter = 2000; warmup = 1000; thin = 1;
#>          total post-warmup draws = 3000
#> 
#> Correlation Structures:
#>                  Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
#> cortime(X08,X10)     0.46      0.14     0.15     0.71 1.00     1766     1808
#> cortime(X08,X12)     0.55      0.13     0.25     0.77 1.00     1865     2199
#> cortime(X10,X12)     0.43      0.15     0.08     0.69 1.00     2007     2106
#> cortime(X08,X14)     0.39      0.16     0.05     0.66 1.00     1675     1901
#> cortime(X10,X14)     0.62      0.12     0.34     0.81 1.00     1907     1897
#> cortime(X12,X14)     0.62      0.12     0.35     0.81 1.00     2109     2260
#> 
#> Population-Level Effects: 
#>                    Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
#> Intercept             21.17      0.71    19.76    22.62 1.00     1516     1838
#> age_fctX10             1.04      0.69    -0.34     2.44 1.00     1273     1540
#> age_fctX12             1.90      0.69     0.50     3.24 1.00     1420     1871
#> age_fctX14             2.89      0.75     1.36     4.40 1.01     1214     1615
#> SexMale                1.71      0.93    -0.13     3.54 1.00     1546     1955
#> age_fctX10:SexMale    -0.10      0.90    -1.86     1.72 1.00     1227     1675
#> age_fctX12:SexMale     0.94      0.90    -0.78     2.77 1.00     1419     1944
#> age_fctX14:SexMale     1.70      0.98    -0.23     3.60 1.00     1185     1602
#> sigma_age_fctX08       0.85      0.14     0.60     1.13 1.00     2121     2342
#> sigma_age_fctX10       0.71      0.13     0.46     0.99 1.00     2002     2045
#> sigma_age_fctX12       0.92      0.14     0.68     1.20 1.00     1949     2055
#> sigma_age_fctX14       0.78      0.13     0.55     1.07 1.00     1843     2039
```

**Some observations and possible issues**

1. First, the estimates are quite close, also the standard errors! The covariances look different, but maybe I missed something here.
2. We might want to add to the documentation how the ordering and the reference of the time variable (character or factor variable) is  determined and that appropriate values need to be chosen to obtain the desired parameterization.
3.  Changing the reference level of the `group`variable  through `level_control` in `brm_data()` did not seem have an effect.
4. When `role = "response"` in `brm_data()`, I understood from the documentation that no `level_baseline = ...` is required, which makes sense to me. However, I received an error  when trying  `level_baseline = NULL`.  (With `effect_baseline = FALSE` and `effect_time = TRUE` in `brm_formula()` the parameterization looked good.)

Perhaps we can briefly discuss this at the next meeting.

**Comment by andrew-bean** [comment]
I tried out both packages briefly last week on the FEV-1 dataset built in to `mmrm`. Similar findings. I can share my code here at some point. 

One comment about this:
> The covariances look different, but maybe I missed something here.

This threw me at first also. The `brms` model for the residual variance involves a linear model for log(sd). The coefficients reported for `sigma_age_fctXXX` are summaries of the posterior for the log(residual sd) at these levels of the covariates. If you exponentiate and then square the medians, you'll probably find they are relatively close to the diagonal elements of the "covariance estimate" output from `mmrm`.

**Comment by chstock** [comment]
Thanks, @andrew-bean for the explanation! Then it's close too. The covariances generally appear to be a bit smaller with the brms.mmrm fit.

**Variances and covariances from mmrm fit**
```r

mmrm_fit["cov"]
#> $cov
#>          08       10       12       14
#> 08 5.415458 2.716820 3.910231 2.710230
#> 10 2.716820 4.184773 2.927161 3.317160
#> 12 3.910231 2.927161 6.455743 4.130742
#> 14 2.710230 3.317160 4.130742 4.985741
```

**Variances from brms.mmrm fit**
```r
summary(brms.mmrm_fit)[["fixed"]] |> 
  as_tibble(rownames = NA) |> 
  rownames_to_column("parameter") |>
  filter(str_detect(parameter, "sigma_")) |>
  select(parameter, Estimate) |>
  mutate(Variance = exp(Estimate)^2)
#> # A tibble: 4 × 3
#>   parameter        Estimate Variance
#>   <chr>               <dbl>    <dbl>
#> 1 sigma_age_fctX08    0.848     5.45
#> 2 sigma_age_fctX10    0.716     4.18
#> 3 sigma_age_fctX12    0.912     6.20
#> 4 sigma_age_fctX14    0.784     4.80
```

**Covariances from brms.mmrm fit**
```r

summary(brms.mmrm_fit)[["cor_pars"]] |> 
  as_tibble(rownames = NA) |> 
  rownames_to_column("cortime") |>
  select(cortime, Estimate) |>
  mutate(Covariance = exp(Estimate)^2)
#> # A tibble: 6 × 3
#>   cortime          Estimate Covariance
#>   <chr>               <dbl>      <dbl>
#> 1 cortime(X08,X10)    0.449       2.46
#> 2 cortime(X08,X12)    0.548       2.99
#> 3 cortime(X10,X12)    0.423       2.33
#> 4 cortime(X08,X14)    0.383       2.15
#> 5 cortime(X10,X14)    0.624       3.48
#> 6 cortime(X12,X14)    0.621       3.46
```

**Comment by wlandau** [comment]
> 4. When role = "response" in brm_data(), I understood from the documentation that no level_baseline = ... is required, which makes sense to me. However, I received an error when trying level_baseline = NULL. (With effect_baseline = FALSE and effect_time = TRUE in brm_formula() the parameterization looked good.)

Sorry about the confusion. The error is correct and the documentation is incorrect. When the outcome variable is the raw response, we need to identify a baseline level so we can produce marginal estimates of change from baseline. Should be fixed in 25bfd4e9a97099c3a463359151837ac36bbea6f1.

**Comment by wlandau** [comment]
> 3. Changing the reference level of the groupvariable through level_control in brm_data() did not seem have an effect.

Yes, `level_control` and `level_baseline` only apply to downstream post-processing functions like `brm_marginal_draws()`. These arguments do not control the fixed effect parameterization that `brms` chooses based on the data and formula.

> 2. We might want to add to the documentation how the ordering and the reference of the time variable (character or factor variable) is determined and that appropriate values need to be chosen to obtain the desired parameterization.

Looking at https://github.com/paul-buerkner/brms/blob/ca12a94a39318c10cdebe96425dc578f9ad926ab/R/data-predictor.R#L977-L996, the fixed effect parameterization seems to come from a call to `model.matrix()` which is called from within `brms::make_standata()`. The `X` field of the output has the fixed effects model matrix.

For our MMRM models with continuous outcomes, the `model.matrix()` call has two arguments: the dataset, and a special formula decorated with attributes which do not seem to affect the processing. `brms` does not seem to expose other arguments, but users can set the `contrasts` option. From `?options`:

> contrasts:
>
>    the default [contrasts](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/contrasts.html) used in model fitting such as with [aov](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/aov.html) or [lm](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/lm.html). A character vector of length two, the first giving the function to be used with unordered factors and the second the function to be used with ordered factors. By default the elements are named c("unordered", "ordered"), but the names are unused.

1652e71e073f118f6d66177fe10a6b47b1a52ccb  adds explanations in the Rd files and usage vignette.

**Comment by chstock** [comment]
> Any outstanding issues with this? Do you think it is a good time to start a vignette with these real data comparisons?

Sounds good to me. Let's perhaps align on Wednesday on datasets and (broadly) model specifications.

**Comment by chstock** [comment]
@wlandau, great answers, thanks!!

**Comment by chstock** [comment]
This issue can be closed.
