### ISSUE TITLE
Expand comparison vignette

### ISSUE THREAD

**Issue by wlandau** [openpharma/brms.mmrm#73]
To continue @chstock's great work from #71, I think we can align closer with https://openpharma.github.io/mmrm/latest-tag/articles/mmrm_review_methods.html. We can analyze the BCVA dataset, and we can discuss our results relative to the ones from https://openpharma.github.io/mmrm/latest-tag/articles/mmrm_review_methods.html#marginal-treatment-effect-estimates-comparison.

**Comment by wlandau** [comment]
A few more comments after rereading both vignettes:

* I noticed that our vignette uses `detectCores()` to choose how many CPU cores to use for the MCMC, whereas CRAN allows at most 2 extra processes.
* The `mmrm` package vignette fits `FEV1 ~ ARMCD * AVISIT + us(AVISIT | USUBJID)`, whereas we fit `FEV1_CHG ~ FEV1_BL + AVISIT + ARMCD:AVISIT + RACE + SEX + us(AVISIT |   USUBJID)`. How important is it to align?
* https://openpharma.github.io/mmrm/latest-tag/articles/mmrm_review_methods.html#marginal-treatment-effect-estimates-comparison reports relative differences. Should we include those as well?
* Likewise, https://openpharma.github.io/mmrm/latest-tag/articles/mmrm_review_methods.html#marginal-treatment-effect-estimates-comparison reports marginal treatment effects. If we reported it in our vignette, I think that would compliment the existing results on the individual model parameters.
* The `mmrm` package appears to give marginal treatment effects which are virtually identical to those of SAS. I am not sure `mmrm` and `brms.mmrm` will agree so closely, and it would be good to include an explanation.

**Comment by wlandau** [comment]
> I noticed that our vignette uses `detectCores()` to choose how many CPU cores to use for the MCMC, whereas CRAN allows at most 2 extra processes.

My mistake, cores are actually capped at 2:

https://github.com/openpharma/brms.mmrm/blob/fe8f4d602b8477a3276b0e0aebf4a89ef5de30ba/vignettes/comparison.Rmd#L205-L209

**Comment by chstock** [comment]
> > I noticed that our vignette uses `detectCores()` to choose how many CPU cores to use for the MCMC, whereas CRAN allows at most 2 extra processes.
> 
> My mistake, cores are actually capped at 2:
> 
> https://github.com/openpharma/brms.mmrm/blob/fe8f4d602b8477a3276b0e0aebf4a89ef5de30ba/vignettes/comparison.Rmd#L205-L209

My idea was to use more cores, but I then figured out that CRAN permits only 2. The code could perhaps be simplified in future revisons.
