### ISSUE TITLE
SBC "checking"

### ISSUE THREAD

**Issue by chstock** [openpharma/brms.mmrm#91]
I saw that a manuscript based on the [preprint on SBC](https://arxiv.org/abs/2211.02383) was accepted and will soon be published in [Bayesian Analysis](https://doi.org/10.1214/23-BA1404):

```
@Article{Modrak2024,
  author  = {Martin Modr{\'a}k and Angie H. Moon and Shinyoung Kim and Paul B{\"u}rkner and Niko Huurre and Kate\v{r}ina Faltejskov{\'a} and Andrew Gelman and Aki Vehtari},
  journal = {Bayesian Analysis},
  title   = {{S}imulation-{B}ased {C}alibration {C}hecking for {B}ayesian {C}omputation: {T}he {C}hoice of {T}est {Q}uantities {S}hapes {S}ensitivity},
  year    = {2024},
  volume  = {forthcoming},
  doi     = {10.1214/23-BA1404},
  url     = {https://doi.org/10.1214/23-BA1404},
}
````

We could add this reference to the respective package [vignette](https://openpharma.github.io/brms.mmrm/articles/sbc.html).

I noticed that the authors refer to SBC "checking": 

> The term in the literature is “simulation-based calibration”; here we have added the word “checking” to emphasize that these methods do not themselves produce calibration; rather, they measure departure from calibration.

I think it would be helpful (for clarity) to refer to SBC "checking" in the vignette too.

**Comment by wlandau** [comment]
Thanks for the FYI. Nice to see an official SBC checking paper will soon be published. Updated the reference and terminology in  https://github.com/openpharma/brms.mmrm/commit/a9581e71e9ed86a25003160082ae234ff8f1ea8b
